server:
  port: 8080
spring:
  data:
    redis:
      host: 192.168.150.102
      port: 6379
      database: 0
      timeout: 3000
  servlet:
    multipart:
      # 单个文件最大大小（根据需要调整，这里设为 50MB）
      max-file-size: 50MB
      # 单次请求最大大小（所有文件总和，这里设为 100MB）
      max-request-size: 100MB
      # 启用文件上传支持（默认开启，可省略）
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/exam_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  glogal-config:
      db-config:
        logic-delete-field: isDeleted

minio:
  endpoint: http://192.168.150.101:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: exam-system

#logging:
#  level:
#    root: debug
doubao:
  base-url: https://ark.cn-beijing.volces.com/api/v3
  api-key: ark-09ac949b-3b16-41e9-b052-573b1a9716a5-f2942
  model: doubao-seed-2-0-lite-260215
  max-tokens: 2000
  temperature: 0.3